version: "3.8"
services:
  db:
    image: postgres:15
    container_name: tcc-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tcc_ambiental
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: tcc-backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached   # monta só o código, não node_modules
    tty: true
    stdin_open: true
    # roda backend automaticamente em background e mantém bash
    command: ["sh", "-c", "npm run dev & bash"]

volumes:
  db_data:
